### ISSUE TITLE
main.lua not found

### ISSUE THREAD

**Issue by ghost** [Moodstocks/gtsrb.torch#3]
Any ideas why I am getting this error: 

> luajit: cannot open main.lua: No such file or directory

I have followed the installation steps as it was here in the github. But it seems like there is no file named main.lua.

**Comment by deltheil** [comment]
There is a [main.lua](https://github.com/Moodstocks/gtsrb.torch/blob/087cf43/main.lua) script at the root of this repository. Once you have cloned, make sure to move to this directory with `cd gtsrb.torch` before running `luajit main.lua`.

**Comment by ghost** [comment]
Oh I was cloning a wrong directory. My bad!
