### ISSUE TITLE
Attempt to call method 'apply'(a nil value)

### ISSUE THREAD

**Issue by yinruiqing** [Moodstocks/gtsrb.torch#4]
Hi,
I am a new in Torch, I try to run the code in AWS, but I met this problem: attempt to call method 'apply'(a nil value)
![error](https://cloud.githubusercontent.com/assets/7274641/13269933/f9c4bf58-da8a-11e5-969c-8ecbf5151e90.PNG)
Can you give me some advices.

**Comment by albanD** [comment]
Do you have the latest version of [nn](https://github.com/torch/nn) ?

**Comment by yinruiqing** [comment]
Hi,
Thank you for your advice. 
I reinstall the nn, but I met another problem. 
`<trainer> on training set:
luajit: ...distro/install/share/lua/5.1/nn/SpatialConvolutionMM.lua:72: attempt to index field 'THNN' (a nil value)`

**Comment by albanD** [comment]
Update `cunn` too :)
