### ISSUE TITLE
STN module error

### ISSUE THREAD

**Issue by Houda-Lam** [Moodstocks/gtsrb.torch#6]
##

**Comment by albanD** [comment]
Hi,

You got this error because CUDA is not installed on your computer.
You must have CUDA installed to be able to install the `stn` package.

**Comment by Houda-Lam** [comment]
is it supported in Mac Book Pro running OS X 10.11 with Intel Iris Pro GPU?

**Comment by albanD** [comment]
No, CUDA is only for Nvidia graphic cards.

**Comment by Houda-Lam** [comment]
thanks a lot.
 I figured that out.
